<!-- Footer -->
<footer>
    <p class="credits">&copy;2013 Longshadow. <a href="#" title="Longshadow">Longshadow</a> by <a href="#" title="Boulder Design Ltd">Boulder Design Ltd</a></p>
</footer>
<!-- End Footer -->

<!-- Back To Top -->
<a id="back-to-top" href="#">
    <i class="font-icon-arrow-simple-up"></i>
</a>
<!-- End Back to Top -->


<!-- Js -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../site/assets/js/jquery-1.10.1.min.js"><\/script>')</script>
<script src="../site/assets/js/waypoints.js"></script> <!-- WayPoints -->
<script src="../site/assets/js/waypoints-sticky.js"></script> <!-- Waypoints for Header -->
<script src="../site/assets/js/jquery.stellar.min.js"></script> <!--  Bootstrap -->
<script src="../site/assets/js/jquery.slicknav.min.js"></script> <!--  responsive mobile menu -->

<script src="../site/assets/js/jquery.tooltipster.min.js"></script> <!-- tooltip for home page image map -->
<script src="../site/assets/js/jquery.backstretch.min.js"></script><!--  background image stretch -->
<script src="../site/assets/js/masonry.pkgd.min.js"></script>
<script src="../site/assets/js/jquery.modal.min.js"></script>
<script src="../site/assets/js/plugins.js"></script> <!-- Contains: jPreloader, jQuery Easing, jQuery ScrollTo, jQuery One Page Navi -->
<script src="../site/assets/js/main.js"></script> <!-- Default JS -->
<!-- End Js -->
<!-- remove when no longer needed
<map name="longshadowmap">
    <area class="homerollover tooltip" shape="rect" coords="100,0,400,300" alt="Bow" href="#" title="Bow">
    <area class="homerollover tooltip" shape="rect" coords="600,0,900,300" alt="Raven" href="#" title="Raven">
    <area class="homerollover tooltip" shape="rect" coords="1000,0,1300,300" alt="Rose" href="#" title="Rose">
</map>
-->
</body>
</html>
